### ISSUE TITLE
samedec: Windows and/or Mac support?

### ISSUE THREAD

**Issue by cbs228** [cbs228/sameold#2]
Right now, `samedec` is only tested on `x86_64-pc-linux-gnu`. It is unclear if it works correctly on Windows, Mac, or other platforms. Most of the instructions are written for linux.

I am unable to provide direct assistance with these other platforms. If `samedec` does not work, and you can contribute platform-specific fixes or advice, please feel free to do so.

**Comment by A-c0rN** [comment]
I can confirm on my end:
Samedec can be compiled for the following and work:
```
x86_64-pc-linux-gnu
aarch64-unknown-linux-gnu
x86_64-pc-windows-gnu
aarch64-apple-darwin*
x86_64-apple-darwin*
```

*With these, I even managed to get `lipo` to compile them together to one "Universal" binary. Works on both Intel and Apple Silicon Macs.

**Comment by cbs228** [comment]
Thanks for testing this! Interestingly, `aarch64-apple-darwin` is not listed as a supported platform for [slice-deque](https://crates.io/crates/slice-deque), which is one of our dependencies. I am pleased to see that it works anyway.

You might try running

```bash
cargo test -p slice-deque
```

on Silicon to make sure all tests pass. If it does, it may be worth dropping the slice-deque [project](https://github.com/gnzlbg/slice_deque) a line to report that it works.

I'm going to go ahead and close this issue since everything appears to be working. If later anyone determines this not to be the case, please re-open or file a new issue.
