### ISSUE TITLE
Closely-spaced EOM/SOM might not decode

### ISSUE THREAD

**Issue by cbs228** [cbs228/sameold#21]
samedec may fail to decode a start-of-message (SOM) if:

1. it is spaced very closely to a preceding end-of-message (EOM); and
2. the first EOM header is missed.

i.e.:

```txt
NNNN
NNNN
ZCZC-WXR-TOR-…
ZCZC-WXR-TOR-…
ZCZC-WXR-TOR-…
```

If the messages are spaced more closely than [`MAX_INTERBURST_GAP_SYMBOLS`](https://github.com/cbs228/sameold/blob/5ef00430d1205e07a76171fc57948ae28b7c1c53/crates/sameold/src/framing.rs#L344), `Framer::bursts` will contain a mixture of EOM and SOM headers. The SOM will be missed.

Handling this situation potentially requires:

* limiting `bursts` to only SOM
* adding some logic to disambiguate
* implementing the fallback decoder from #4.

**Comment by cbs228** [comment]
Hey @A-c0rN, as our resident ENDEC expert, have you observed this transmitter misbehavior before on NWR or anywhere else?

**Comment by A-c0rN** [comment]
I don't think I've ever seen this, and I haven't experienced it in samedec either. I've been using this software for months straight, and have never seen this.

**Comment by A-c0rN** [comment]
If this is happening consistently on your end, I would check your audio chain.

**Comment by cbs228** [comment]
> I don't think I've ever seen this

… and apparently, neither have I. Some additional forensics indicate that the transmitter did *not* intermingle messages. There appears to be a corner case in the framer involving a missed EOM that is immediately proceeded by an SOM. See new issue description.

This is likely *very* rare, which is why neither of us have seen it before.  I'm going to have to re-work the framing logic a bit to cover cases like this.
